name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Push to destination repository
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.WRITE_TOKEN }}
        branch: FineScore
        repository: Coding-Test-Random-Defence/Bronze-4-to-Silver-5
        directory: ./
